neo_neo_hazardous:
    path: /neo/hazardous
    controller: App\Neo\NeoBundle\Controller\DefaultController::hazardous

neo_neo_fastest:
    path: /neo/fastest
    controller: App\Neo\NeoBundle\Controller\DefaultController::fastest

neo_neo_fastest_hazardous:
    path: /neo/fastest/hazardous
    controller: App\Neo\NeoBundle\Controller\DefaultController::fastestHazardous

neo_neo_best_year:
    path: /neo/best-year
    controller: App\Neo\NeoBundle\Controller\DefaultController::bestYear
