index:
    path: /
    controller: App\Controller\DefaultController::index

hello:
    path: /hello
    controller: App\Controller\DefaultController::hello

neo_neobundle_routes:
    resource: '@NeoNeoBundle/Resources/config/routes.yaml'
